### ISSUE TITLE
Failure validating on empty ipv6 subnet list

### ISSUE THREAD

**Issue by mickrau** [friendly-bits/geoip-shell#13] opened 2024-07-25 08:16 UTC
I got an error when validating KP_ipv6 from RIPE.
I suspect this is because there are no ipv6 subnets for KP.

```
Fetching ip list for country 'KP' from RIPE...
###################################################################################################################################################################################################################################### 100.0%
Fetch successful.
 
Parsing ip list for 'KP_ipv4'... Ok.
Validating 'KP_ipv4'... Ok.
Validated subnets for 'KP_ipv4': 1.
 
Parsing ip list for 'KP_ipv6'... Ok.
Validating 'KP_ipv6'...
fetch: Error: NOTE: out of 10 subnets for ip list 'KP_ipv6, 10 subnets failed validation'.
Following subnets failed validation:
        }
    },
query_id
process_time
server_id
build_version
status
status_code
time
}
 
Failed.
run: Error: Failed to fetch and validate lists 'KP_ipv6'.
run: Warning: Aborting the action 'add'.
manage: Warning: Discrepancy detected between the firewall state and the config file.
``
`

**Comment by friendly-bits** [comment] 2024-07-25 08:24
Thank you for reporting this. Indeed, looks like there are no ipv6 subnets for KP and this is what's causing the issue. I'll implement support for per-country ipv6 exclusions.

**Comment by friendly-bits** [comment] 2024-07-25 09:24
I just discovered that there is also a bug which is preventing successful recovery of previous ip lists when ip lists change fails. I'll release a new version fixing this soon.

**Comment by friendly-bits** [comment] 2024-07-25 16:03
@mickrau I just released version 0.5.5 which fixes both issues: previous ip lists recovery when changes fail, and handling of country codes which only have subnets of 1 ip family. This release includes a new file - `iplist-exclusions.conf` which is used to specify excluded ip list id's (where ip list id has the format `<country_code>_<family>`, for example `KP_ipv6` - currently the only exclusion).

Please confirm that the issue is resolved.

**Comment by friendly-bits** [comment] 2024-07-30 18:46
I'm closing this issue because I can not reproduce it anymore since v0.5.5 release. If you find that it still affects you, please feel free to reopen.

**Closed by friendly-bits** 2024-07-30 18:46 UTC

**Comment by mickrau** [comment] 2024-07-31 11:39
@friendly-bits works fine. Thank you
